In [ ]:
>>> import numpy as np
>>> np.random.seed(0);np.random.rand(3)
array([ 0.5488135 ,  0.71518937,  0.60276338])
>>> np.random.seed(0);np.random.rand(3)
array([ 0.5488135 ,  0.71518937,  0.60276338])
# You may set any number to seed 
>>> np.random.seed(2);np.random.rand(3)
array([ 0.4359949 ,  0.02592623,  0.54966248])
>>> np.random.seed(2);np.random.rand(3)
array([ 0.4359949 ,  0.02592623,  0.54966248])

In [ ]:
>>> np.random.rand(3)
array([ 0.43532239,  0.4203678 ,  0.33033482])
>>> np.random.rand(3)
array([ 0.20464863,  0.61927097,  0.29965467])