<a href="https://colab.research.google.com/github/shahidakhtarkhan/binarystudy.github.io/blob/main/SparseMatrixMultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Python program to multpliply two 
# csr matrices using multiply()

# Import required libraries
import numpy as np
from scipy.sparse import csr_matrix

# Create first csr matrix A

row_A = np.array([0, 0, 1, 2 ])
col_A = np.array([0, 1, 0, 1])

data_A = np.array([4, 3, 8, 9])

csrMatrix_A = csr_matrix((data_A, (row_A, col_A)),
						shape = (3, 3))
# print first csr matrix
print("first csr matrix: \n", csrMatrix_A.toarray())

# Create second csr matrix B

row_B = np.array([0, 1, 1, 2 ])
col_B = np.array([0, 0, 1, 0])

data_B = np.array([7, 2, 5, 1])

csrMatrix_B = csr_matrix((data_B, (row_B, col_B)),
						shape = (3, 3))
# print second scr matrix
print("second csr matrix:\n", csrMatrix_B.toarray())

# Multiply these matrices
sparseMatrix_AB = csrMatrix_A.multiply(csrMatrix_B)

# print resultant matrix
print("Product Sparse Matrix:\n",sparseMatrix_AB.toarray() )


first csr matrix: 
 [[4 3 0]
 [8 0 0]
 [0 9 0]]
second csr matrix:
 [[7 0 0]
 [2 5 0]
 [1 0 0]]
Product Sparse Matrix:
 [[28  0  0]
 [16  0  0]
 [ 0  0  0]]


In [10]:
# Python program to multpliply two 
# csc matrices using multiply()

# Import required libraries
import numpy as np
from scipy.sparse import csc_matrix

# Create first csc matrix A

row_A = np.array([0, 0, 1, 2 ])
col_A = np.array([0, 1, 0, 1])

data_A = np.array([4, 3, 8, 9])

cscMatrix_A = csc_matrix((data_A, (row_A, col_A)),
						shape = (3, 3))
# print first csc matrix
print("first csc matrix: \n", cscMatrix_A.toarray())

# Create second csc matrix B

row_B = np.array([0, 1, 1, 2 ])
col_B = np.array([0, 0, 1, 0])

data_B = np.array([7, 2, 5, 1])

cscMatrix_B = csc_matrix((data_B, (row_B, col_B)),
						shape = (3, 3))
# print second csc matrix
print("second csc matrix:\n", cscMatrix_B.toarray())

# Multiply these matrices
sparseMatrix_AB = cscMatrix_A.multiply(cscMatrix_B)

# print resultant matrix
print("Product Sparse Matrix:\n",sparseMatrix_AB.toarray() )


first csc matrix: 
 [[4 3 0]
 [8 0 0]
 [0 9 0]]
second csc matrix:
 [[7 0 0]
 [2 5 0]
 [1 0 0]]
Product Sparse Matrix:
 [[28  0  0]
 [16  0  0]
 [ 0  0  0]]


In [11]:
# Python program to multpliply  
# csc and csr matrices using multiply()

# Import required libraries
import numpy as np
from scipy.sparse import csc_matrix

# Create csc matrix

row_A = np.array([0, 0, 1, 2 ])
col_A = np.array([0, 1, 0, 1])

data_A = np.array([4, 3, 8, 9])

cscMatrix = csc_matrix((data_A, (row_A, col_A)),
						shape = (3, 3))
# print  csc matrix
print("csc matrix: \n", cscMatrix.toarray())

# Create csr matrix 

row_B = np.array([0, 1, 1, 2 ])
col_B = np.array([0, 0, 1, 0])

data_B = np.array([7, 2, 5, 1])

csrMatrix_B = csc_matrix((data_B, (row_B, col_B)),
						shape = (3, 3))
# print csr matrix
print("csr matrix:\n", csrMatrix_B.toarray())

# Multiply csc matrix with csr matrix
sparseMatrix = cscMatrix_A.multiply(csrMatrix_B)
# print resultant matrix
print("Product csc with csr Matrix:\n",sparseMatrix.toarray() )

# Multiply csr matrix with csc matrix
sparseMatrix = csrMatrix_A.multiply(cscMatrix_B)
# print resultant matrix
print("Product csr with csc Matrix:\n",sparseMatrix.toarray() )


csc matrix: 
 [[4 3 0]
 [8 0 0]
 [0 9 0]]
csr matrix:
 [[7 0 0]
 [2 5 0]
 [1 0 0]]
Product csc with csr Matrix:
 [[28  0  0]
 [16  0  0]
 [ 0  0  0]]
Product csr with csc Matrix:
 [[28  0  0]
 [16  0  0]
 [ 0  0  0]]
